<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Marten" Version="8.37.0"/>
        <PackageReference Include="MediatR" Version="14.1.0"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\XpensTrack\src\Shared\Shared.csproj"/>
    </ItemGroup>

</Project>
