namespace Shared.Contracts;

public record TransactionUpdatedIntegrationEvent(
    Guid TransactionId,
    Guid OldWalletId,
    string UserId,
    decimal OldAmount,
    string OldAmountCurrencyCode,
    decimal OldDefaultCurrencyAmount,
    string OldDefaultCurrencyCode,
    string OldTransactionType,
    string? OldTransactionCategory,
    string OldDescription,
    DateTimeOffset OldOccuredAt,
    Guid? OldToWalletId,
    decimal? OldToWalletAmount,
    string? OldToWalletAmountCurrencyCode,
    decimal? OldToWalletCurrencyExchangeRate,
    string? OldToWalletCurrencyCode,
    Guid NewWalletId,
    decimal NewWalletExchangeRate,
    string NewWalletCurrencyCode,
    decimal NewAmount,
    string NewAmountCurrencyCode,
    decimal NewDefaultCurrencyAmount,
    string NewDefaultCurrencyCode,
    string NewTransactionType,
    string? NewTransactionCategory,
    string NewDescription,
    DateTimeOffset NewOccurredAt,
    Guid? NewToWalletId,
    decimal? NewToWalletAmount,
    string? NewToWalletAmountCurrencyCode,
    decimal? NewToWalletCurrencyExchangeRate,
    string? NewToWalletCurrencyCode
);
